[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cloud_sheets_slim"
version = "0.1.2"
authors = [{name = "Ying Cai", email = "i@caiying.me"}]
description = "A lightweight cloud sheets operation library"
readme = "README.md"
dependencies = [
    "gspread",
    "pandas",
    "oauth2client",
    "python-dotenv"
]
